# PostgreSQL

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: thiago
  password: thiago
  timeout: 5000

development:
  <<: *default
  database: db_billinho
test:
  <<: *default
  database: db_billinho

production:
  <<: *default
  database: db_billinho