# PostgreSQL 12

development:
  adapter: postgresql
  database: dev_db
  username: postgres
  password: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: test_db
  username: postgres
  password: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: prod_db
  username: postgres
  password: postgres
  min_messages: warning
