# PostgreSQL 12

development:
  adapter: postgresql
  database: dev
  username: postgres
  password: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: test
  username: postgres
  password: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: prod
  username: postgres
  password: postgres
  min_messages: warning
