# PostgreSQL 12

development:
  adapter: postgresql
  database: db_development
  username: postgres
  password: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: db_test
  username: postgres
  password: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: db_production
  username: postgres
  password: postgres
  min_messages: warning
