# PostgreSQL 12

development:
  adapter: postgresql
  database: billinho_dev
  username: postgres
  password: postgres
  min_messages: warning

test:
  adapter: postgresql
  database: billinho_test
  username: postgres
  password: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: billinho_prod
  username: postgres
  password: postgres
  min_messages: warning
